version: "3.3"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /Users/djalyarim/Dev/middle-developer/Admin_panel_sprint_1/pgdata:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050





# services:
#   db:
#     container_name: postgres
#     image: postgres:13
#     restart: always
#     volumes:
#       - /Users/djalyarim/Dev/middle-developer/Admin_panel_sprint_1/pgdata:/var/lib/postgresql/data
#     env_file:
#       - .env


      